language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.1
  - 3.2
install: 
  - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors simplejson; fi
  - pip install .
  - pip install pytest --use-mirrors
script: py.test tests
